version: '3'
services:
  test:
    build:
      context: ./api
      dockerfile: Dockerfile-mocha
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - "9000:9000"
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
