version: '3'
services:
  api:
    build: ./api
    ports:
      - "9000"
    depends_on:
      - db
  web:
    build: ./web
    ports:
      - "8080:80"
    depends_on:
      - api
  db:
    build: ./db
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
