version: '3'

services:
  test:
    build:
      context: ./api
      dockerfile: Dockerfile-mocha
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - "9000"
    depends_on:
      - db
    # logging:
    #   # disable logging to allow test output to be readable
    #   # TODO: find a better solution
    #   driver: none
  db:
    build: ./db
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # logging:
    #   # disable logging to allow test output to be readable
    #   # TODO: find a better solution
    #   driver: none
